# Generated by Django 5.2.6 on 2025-10-08 23:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('nome', models.CharField(max_length=25)),
                ('sobrenome', models.CharField(max_length=25)),
                ('email', models.EmailField(max_length=254, primary_key=True, serialize=False, unique=True)),
                ('telefone', models.CharField(max_length=15)),
                ('senha', models.CharField(max_length=100)),
            ],
        ),
    ]
